name = "hono-runtime"
main = "index.js"
compatibility_date = "2023-03-01"

# Site setting for static files are set here BUT it does not include any files by default.
# This is because hono-runtime exports staticServe() which makes wrangler scans this setting to create a manifest list of static files.
# Since there's no easy way to override wrangler's behavior, we just include this benign setting.
[site]
bucket = "./"
include = [""]